export const COLORS = [
  { label: 'Preto', value: 'black', hex: '#000000' },
  { label: 'Branco', value: 'white', hex: '#ffffff' },
  { label: 'Prata', value: 'silver', hex: '#949494' },
  { label: 'Vermelho', value: 'red', hex: '#ed3434' },
  { label: 'Laranja', value: 'orange', hex: '#ff7c12' },
  { label: 'Amarelo', value: 'yellow', hex: '#ffec17' },
  { label: 'Dourado', value: 'gold', hex: '#ffd700' },
  { label: 'Marrom', value: 'brown', hex: '#965927' },
  { label: 'Salmão', value: 'salmon', hex: '#fa7f72' },
  { label: 'Bege', value: 'beige', hex: '#f5f5dc' },
  { label: 'Vinho', value: 'burgundy', hex: '#5e2129' },
  { label: 'Roxo', value: 'purple', hex: '#993399' },
  { label: 'Violeta', value: 'violet', hex: '#7f00ff' },
  { label: 'Rosa choque', value: 'hotpink', hex: '#fc0fc0' },
  { label: 'Rosa claro', value: 'lightpink', hex: '#ff7dd8' },
  { label: 'Lilás', value: 'lilac', hex: '#c8a2c8' },
  { label: 'Lavanda', value: 'lavender', hex: '#e6e6fa' },
  { label: 'Azul marinho', value: 'navy', hex: '#120a8f' },
  { label: 'Azul furtivo', value: 'dodgerblue', hex: '#1e90ff' },
  { label: 'Azul céu', value: 'skyblue', hex: '#69b5ff' },
  { label: 'Verde lima', value: 'limegreen', hex: '#32cd32' },
  { label: 'Verde amarelado', value: 'yellowgreen', hex: '#9acd32' },
  { label: 'Esmeralda', value: 'emerald', hex: '#50c878' },
  { label: 'Ciano', value: 'cyan', hex: '#00ffff' },
  { label: 'Ciano escuro', value: 'darkcyan', hex: '#008b8b' },
  { label: 'Ciano claro', value: 'lightcyan', hex: '#a8ffff' },
  { label: 'Cinza claro', value: 'lightgray', hex: '#d3d3d3' },
  { label: 'Creme', value: 'cream', hex: '#fffdd0' },
  { label: 'Pêssego', value: 'peach', hex: '#ffcba4' },
  { label: 'Rosa bebê', value: 'baby-pink', hex: '#ffb6c1' },
  { label: 'Turquesa', value: 'turquoise', hex: '#40e0d0' },
  { label: 'Magenta', value: 'magenta', hex: '#ff00ff' },
  { label: 'Coral', value: 'coral', hex: '#ff7f50' },
  { label: 'Vermelho cereja', value: 'cherry-red', hex: '#d2042d' },
  { label: 'Mostarda', value: 'mustard', hex: '#ffdb58' },
  { label: 'Azul petróleo', value: 'teal', hex: '#2f4f4f' },
  { label: 'Vermelho rubi', value: 'ruby-red', hex: '#9b111e' },
  { label: 'Verde oliva', value: 'olive', hex: '#808000' },
  { label: 'Azul céu claro', value: 'light-sky-blue', hex: '#87ceeb' },
  { label: 'Rosa pastel', value: 'pastel-pink', hex: '#f7b7d4' },
  { label: 'Azul claro', value: 'lightblue', hex: '#add8e6' },
  { label: 'Bege rosado', value: 'rose-beige', hex: '#f2d1c9' },
  { label: 'Pêssego claro', value: 'light-peach', hex: '#ffdab9' },
  { label: 'Verde menta', value: 'mint-green', hex: '#98ff98' },
];
